// Flavour-only name pools for auto-naming drafted players, grouped by a coarse
// "naming culture" each team belongs to. These are original coinages in the
// style of each faction — not codex data and not localized, so they live with
// the builder rather than in @blitz/data.

const cultureTeams = {
  greenskin: ['orc', 'black-orc', 'goblin', 'snotling'],
  elf: ['dark-elf', 'elven-union', 'high-elf', 'wood-elf'],
  human: ['human', 'bretonnian', 'imperial-nobility', 'old-world-alliance'],
  dwarf: ['dwarf', 'chaos-dwarf'],
  norse: ['norse'],
  chaos: ['chaos-chosen', 'chaos-renegades', 'khorne', 'nurgle'],
  undead: ['necromantic-horror', 'shambling-undead', 'vampire'],
  khemri: ['tomb-kings'],
  lustrian: ['amazon', 'lizardmen', 'slann'],
  ratkin: ['skaven', 'underworld-denizens'],
  smallfolk: ['halfling', 'gnome'],
  ogre: ['ogre'],
} satisfies Record<string, readonly string[]>

type NamingCulture = keyof typeof cultureTeams

const teamCulture = new Map<string, NamingCulture>(
  Object.entries(cultureTeams).flatMap(([culture, keys]) =>
    keys.map((key) => [key, culture as NamingCulture])
  )
)

// Sixteen names per culture — a full 16-player roster draws unique names without
// repeats, since drafting never exceeds the roster cap.
const namePools: Record<NamingCulture, readonly string[]> = {
  greenskin: [
    'Grukk Bonesplitter',
    'Urgath Skullcrack',
    'Morglok Ironjaw',
    'Gritlob Gutbuster',
    'Snik Backstabba',
    'Wartz Eyegouger',
    'Brakka Stomp',
    'Drog Skarface',
    'Ugzog Smasha',
    'Krunch Headbutt',
    'Zogrim Gutripper',
    'Nazga Toothsnatcha',
    'Gormek Facebiter',
    'Skab Mangla',
    'Thrugg Crushfist',
    'Hagrok Bloodtusk',
  ],
  elf: [
    'Caradril Dawnstar',
    'Elenwë Brightspear',
    'Faelyn Nightbreeze',
    'Thandor Greenbough',
    'Aerendyl Stormcrest',
    'Maeglin Ravenwing',
    'Sariel Windrunner',
    'Galathil Sunwhisper',
    'Elrohin Mistwalker',
    'Nimriel Quickfoot',
    'Celenor Ashleaf',
    'Idriel Goldbough',
    'Aelindra Swiftwind',
    'Lothir Moonshade',
    'Faenor Silverleaf',
    'Vaeril Starfall',
  ],
  human: [
    'Gunnar Brandt',
    'Reinhardt Vogel',
    'Aldric Sommer',
    'Wilhelm Stein',
    'Otto Krüger',
    'Marius Vendel',
    'Karl Hochberg',
    'Friedrich Maur',
    'Lothar Brand',
    'Sigmund Reik',
    'Bertrand Roche',
    'Anselm Faber',
    'Konrad Stahl',
    'Emil Vogt',
    'Dietrich Falk',
    'Gerard Lyon',
  ],
  dwarf: [
    'Thorgan Stoutarm',
    'Grimli Stonefist',
    'Durak Anvilbrow',
    'Bardin Ironbeard',
    'Kazrik Goldhammer',
    'Borin Deepdelve',
    'Thrund Coalbeard',
    'Snorri Hammerhand',
    'Drong Steelboot',
    'Ulfgar Forgeheart',
    'Bromm Axebite',
    'Khaldrim Emberforge',
    'Gottri Rockfist',
    'Skarn Hearthborn',
    'Durgan Oathstone',
    'Brokk Deepmokk',
  ],
  norse: [
    'Bjorn Frosthammer',
    'Sven Ironside',
    'Ragnar Wolfskin',
    'Ulf Stormborn',
    'Erik Bloodaxe',
    'Knut Bearclaw',
    'Halfdan Snowbeard',
    'Leif Seawolf',
    'Sigurd Frostmane',
    'Olaf Thunderfist',
    'Torsten Grimsson',
    'Harald Icevein',
    'Bothvar Bearson',
    'Eivind Skullcleaver',
    'Gunnvald Stormhowl',
    'Asger Wavebreaker',
  ],
  chaos: [
    'Vorgath the Defiler',
    'Khargûl Bloodmaw',
    'Zarakk Skulltaker',
    'Drathoz Hellforge',
    'Vexis Darkbane',
    'Throgmar Rotgut',
    'Malkor the Cruel',
    'Sceoth Doomcaller',
    'Gharne Fleshrender',
    'Azmoth Blackheart',
    'Korruth Painbringer',
    'Vandrid the Profane',
    'Slaurug Pusboil',
    'Nethrax Souleater',
    'Vaelkor Grimscar',
    'Hexus Wraithcall',
  ],
  undead: [
    'Count Vladis Mortis',
    'Morvann Graveborn',
    'Vlash Nachtsturm',
    'Isabeau Pale',
    'Rasmus Cryptkeeper',
    'Morgaine Tombshade',
    'Dietrich Grimm',
    'Carmilla Nightveil',
    'Lothar Coldgrave',
    'Lenora Bloodtear',
    'Konrad Ghoulheart',
    'Helga Mortgrave',
    'Brakus Bonepile',
    'Grymm Pallid',
    'Otto Rotvein',
    'Selka Wraithmoor',
  ],
  khemri: [
    'Sethapris the Undying',
    'Khalibel Sunseeker',
    'Arkhem Dustcrown',
    'Sekhep the Withered',
    'Ankhet Sandshroud',
    'Nefret Goldmask',
    'Ramesh Boneshard',
    'Khaleth Scarab',
    'Imhetep the Bound',
    'Userib Sandborn',
    'Tutankh Dryflesh',
    'Menkara Sunken',
    'Sobek Reedwalker',
    'Hapu Tombwarden',
    'Amunhotek Sunfall',
    'Djoser Sandking',
  ],
  lustrian: [
    'Tlaloc Sunscale',
    'Itzcoatl Greentooth',
    'Xola Jadeclaw',
    'Quetz Stoneskin',
    'Inaki Vinerunner',
    'Zoltek Swamptongue',
    'Citlali Moonjaguar',
    'Nuakin Riverback',
    'Coatl Featherspine',
    'Yaxha Thornhide',
    'Tletl Emberscale',
    'Acalan Mudfist',
    'Xibal Nightcoil',
    'Mixcoa Sunspear',
    'Tepeu Rootbinder',
    'Ixchel Rainfeather',
  ],
  ratkin: [
    'Skritch Quickfang',
    'Verm Gutterscamp',
    'Skarrick Plaguepaw',
    'Snitch Tailbiter',
    'Skab Twistedtail',
    'Ratchit Cogfinger',
    'Snik Backbiter',
    'Throt Festerclaw',
    'Squick Nightscamp',
    'Krisst Warptooth',
    'Gnaw Cheesethief',
    'Skrim Sneakwhisker',
    'Vresh Poxscratch',
    'Klawd Scurrytail',
    'Skreet Foulwhisker',
    'Nibble Wiretooth',
  ],
  smallfolk: [
    'Pippin Puddlefoot',
    'Tobias Greenhill',
    'Milo Barleycorn',
    'Drogo Honeypot',
    'Wilbur Thornberry',
    'Nob Hayward',
    'Perry Dimplewick',
    'Fenwick Tanglebriar',
    'Cosmo Burrows',
    'Marigold Quickstep',
    'Tuck Applewood',
    'Bingo Mossbottom',
    'Pock Tumblewheat',
    'Errol Figglesworth',
    'Hamish Brambletoe',
    'Dilly Copperkettle',
  ],
  ogre: [
    'Brak Stonejaw',
    'Grull Bonebreak',
    'Mungo Skullthump',
    'Crush Heavyfist',
    'Grom Bigbelly',
    'Throk Manmangler',
    'Bulgar Stonegut',
    'Krunk Tallclub',
    'Gorm Treesnapper',
    'Drubb Rockhead',
    'Hagar Mightyjaw',
    'Borgo Hugefist',
    'Ulk Groundshaker',
    'Thump Lumberfoot',
    'Murgan Boulderhand',
    'Gronk Ironbelly',
  ],
}

/**
 * A random faction-appropriate name for a freshly drafted player. Names already
 * in `exclude` are skipped so a roster reads with no duplicates; an unknown team
 * key falls back to the human pool.
 */
export function randomPlayerName(
  teamKey: string,
  exclude: Iterable<string> = []
): string {
  const pool = namePools[teamCulture.get(teamKey) ?? 'human']
  const used = new Set(exclude)
  const free = pool.filter((name) => !used.has(name))
  const choices = free.length > 0 ? free : pool
  return choices[Math.floor(Math.random() * choices.length)]
}
